# Generated by Django 3.2.18 on 2023-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20230413_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapis',
            name='is_translated',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
