# Generated by Django 3.2.18 on 2023-04-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_comment_is_translated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='TranslatedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_body', models.TextField(default='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_comments', to='crud.comment')),
            ],
        ),
    ]
